spec:
  replicas: 1
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
  - type: ConfigChange
  template:
    spec:
      containers:
        - name: ${project.artifactId}
          env:
          - name: POSTGRESQL_USER
            value: mjopadmin
          - name: POSTGRESQL_PASSWORD
            value: mjopadmin
          - name: POSTGRESQL_DATABASE
            value: mjopelements
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
        - name: ${project.artifactId}-db
          env:
          - name: POSTGRESQL_USER
            value: mjopadmin
          - name: POSTGRESQL_PASSWORD
            value: mjopadmin
          - name: POSTGRESQL_DATABASE
            value: mjopelements
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
